site_name: effdsl
site_url: https://sdqri.org/effdsl
theme:
  name: material
  palette:
  - media: "(prefers-color-scheme)"
    toggle:
      icon: material/lightbulb-auto
      name: Switch to light mode
  - media: '(prefers-color-scheme: light)'
    scheme: default
    primary: cyan
    accent: deep purple
    toggle:
      icon: material/lightbulb
      name: Switch to dark mode
  - media: '(prefers-color-scheme: dark)'
    scheme: slate
    primary: cyan
    accent: deep purple
    toggle:
      icon: material/lightbulb-outline
      name: Switch to system preference
  features:
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.path
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
repo_name: sdqri/effdsl
repo_url: https://github.com/sdqri/effdsl
nav:
  - effdsl: 
    - index.md
    - Compound Queries:
      - bool_query.md
      - boosting_query.md
      - constant_score.md
      - dis_max_query.md
    - Full Text Queries:
      - match_query.md
      - match_bool_prefix.md
      - match_phrase_query.md
      - match_phrase_prefix.md
      - multi_match_query.md
      - query_string.md
      - simple_query_string.md
    - match_all_query.md
    - Term-Level Queries:
      - exists_query.md
      - fuzzy_query.md
      - ids_query.md
      - prefix_query.md
      - range_query.md
      - regexp_query.md
      - term_query.md
      - terms_query.md
      - terms_set_query.md
      - wildcard_query.md
    - Joining Queries:
      - nested_query.md
    - Suggesters:
      - completion_suggester.md
      - phrase_suggester.md
      - term_suggester.md
    - Aggregations:
      - adjacency_matrix_aggregation.md
      - auto_date_histogram_aggregation.md
      - avg_aggregation.md
      - boxplot_aggregation.md
      - cartesian_bounds_aggregation.md
      - date_histogram_aggregation.md
      - cartesian_centroid_aggregation.md
      - date_range_aggregation.md
      - cardinality_aggregation.md
      - extended_stats_aggregation.md
      - geo_bounds_aggregation.md
      - geo_centroid_aggregation.md
      - geo_line_aggregation.md
      - matrix_stats_aggregation.md
      - max_aggregation.md
      - median_absolute_deviation_aggregation.md
      - min_aggregation.md
      - percentile_ranks_aggregation.md
      - percentiles_aggregation.md
      - rate_aggregation.md
      - scripted_metric_aggregation.md
      - stats_aggregation.md
      - string_stats_aggregation.md
      - t_test_aggregation.md
      - top_hits_aggregation.md
      - top_metrics_aggregation.md
      - value_count_aggregation.md
      - weighted_avg_aggregation.md
      - sum_aggregation.md
  - API Coverage: api_coverage.md
  - Release Notes: release_notes.md
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
